name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v4
    
     - name: Install Qt
       uses: jurplel/install-qt-action@v3
       with:
         version: '5.15.2'
         host: 'windows'
         target: 'desktop'
         arch: 'win64_msvc2019_64'
         dir: '${{ github.workspace }}/qt'
         install-deps: 'true'
         modules: 'qtcharts qtwebengine'
         archives: 'qtbase qtsvg'
         cache: 'true'
         cache-key-prefix: 'install-qt-action'
         setup-python: 'true'
         tools: 'tools_ifw tools_qtcreator,qt.tools.qtcreator'
         set-env: 'true'
         tools-only: 'false'
         aqtversion: '==3.1.*'
         py7zrversion: '==0.20.*'
         extra: '--external 7z'

     - uses: ilammy/msvc-dev-cmd@v1
       with:
         vsversion: "2019"
     - name: Build
       run: |
          msbuild 'GH Injector GUI.sln'
      
